import { CreateSpectacleDto } from './dto/create-spectacle.dto';

export const mockSpectacleData: CreateSpectacleDto[] = [
  {
    id: '6253',
    idw: '310',
    nazwa: 'Inteligenci',
    rezyseria: 'reż. Radosław B. Maciąg',
    czas_trwania_min: '120',
    data: '20-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6253',
  },
  {
    id: '6265',
    idw: '325',
    nazwa: 'Balkon',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '180',
    data: '20-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6265',
  },
  {
    id: '6266',
    idw: '325',
    nazwa: 'Balkon',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '180',
    data: '21-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6266',
  },
  {
    id: '6297',
    idw: '310',
    nazwa: 'Inteligenci',
    rezyseria: 'reż. Radosław B. Maciąg',
    czas_trwania_min: '120',
    data: '21-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6297',
  },
  {
    id: '6263',
    idw: '283',
    nazwa: 'Zaczarowana królewna',
    rezyseria: 'reż. Michał Derlatka',
    czas_trwania_min: '95',
    data: '22-07-2022',
    godzina: '10:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '17',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6263',
  },
  {
    id: '6264',
    idw: '283',
    nazwa: 'Zaczarowana królewna',
    rezyseria: 'reż. Michał Derlatka',
    czas_trwania_min: '95',
    data: '23-07-2022',
    godzina: '11:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '34',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6264',
  },
  {
    id: '6267',
    idw: '325',
    nazwa: 'Balkon',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '180',
    data: '23-07-2022',
    godzina: '18:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '1',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6267',
  },
  {
    id: '6268',
    idw: '325',
    nazwa: 'Balkon',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '180',
    data: '24-07-2022',
    godzina: '18:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6268',
  },
  {
    id: '6272',
    idw: '331',
    nazwa: 'Resztki',
    rezyseria: 'reż. Ewelina Marciniak',
    czas_trwania_min: '120',
    data: '26-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '27',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6272',
  },
  {
    id: '6269',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '26-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6269',
  },
  {
    id: '6270',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '27-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6270',
  },
  {
    id: '6273',
    idw: '331',
    nazwa: 'Resztki',
    rezyseria: 'reż. Ewelina Marciniak',
    czas_trwania_min: '120',
    data: '27-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '42',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6273',
  },
  {
    id: '6271',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '28-07-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6271',
  },
  {
    id: '6274',
    idw: '322',
    nazwa: 'Lilla Weneda',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '03-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '56',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6274',
  },
  {
    id: '6275',
    idw: '322',
    nazwa: 'Lilla Weneda',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '04-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '19',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6275',
  },
  {
    id: '6306',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '05-08-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6306',
  },
  {
    id: '6276',
    idw: '322',
    nazwa: 'Lilla Weneda',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '05-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '59',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6276',
  },
  {
    id: '6277',
    idw: '322',
    nazwa: 'Lilla Weneda',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '06-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '60',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6277',
  },
  {
    id: '6278',
    idw: '322',
    nazwa: 'Lilla Weneda',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '07-08-2022',
    godzina: '18:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '59',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6278',
  },
  {
    id: '6305',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '09-08-2022',
    godzina: '20:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '36',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6305',
  },
  {
    id: '6281',
    idw: '336',
    nazwa: 'Bunbury. Komedia dla ludzi bez poczucia humoru',
    rezyseria: 'reż. Kuba Kowalski',
    czas_trwania_min: '105',
    data: '10-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '18',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6281',
  },
  {
    id: '6282',
    idw: '336',
    nazwa: 'Bunbury. Komedia dla ludzi bez poczucia humoru',
    rezyseria: 'reż. Kuba Kowalski',
    czas_trwania_min: '105',
    data: '11-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6282',
  },
  {
    id: '6279',
    idw: '334',
    nazwa: 'Nieczułość',
    rezyseria: 'reż. Lena Frankiewicz ',
    czas_trwania_min: '115',
    data: '11-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '31',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6279',
  },
  {
    id: '6304',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '11-08-2022',
    godzina: '20:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '1',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6304',
  },
  {
    id: '6280',
    idw: '334',
    nazwa: 'Nieczułość',
    rezyseria: 'reż. Lena Frankiewicz ',
    czas_trwania_min: '115',
    data: '12-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '71',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6280',
  },
  {
    id: '6283',
    idw: '336',
    nazwa: 'Bunbury. Komedia dla ludzi bez poczucia humoru',
    rezyseria: 'reż. Kuba Kowalski',
    czas_trwania_min: '105',
    data: '12-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '41',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6283',
  },
  {
    id: '6303',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '12-08-2022',
    godzina: '20:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '73',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6303',
  },
  {
    id: '6314',
    idw: '328',
    nazwa: 'Awantura w Chioggi',
    rezyseria: 'reż. Paweł Aigner',
    czas_trwania_min: '135',
    data: '13-08-2022',
    godzina: '18:00',
    miejsce: 'Gdański Teatr Szekspirowski',
    miejsca_dostepne: '263',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6314',
  },
  {
    id: '6315',
    idw: '328',
    nazwa: 'Awantura w Chioggi',
    rezyseria: 'reż. Paweł Aigner',
    czas_trwania_min: '135',
    data: '14-08-2022',
    godzina: '18:00',
    miejsce: 'Gdański Teatr Szekspirowski',
    miejsca_dostepne: '305',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6315',
  },
  {
    id: '6284',
    idw: '336',
    nazwa: 'Bunbury. Komedia dla ludzi bez poczucia humoru',
    rezyseria: 'reż. Kuba Kowalski',
    czas_trwania_min: '105',
    data: '14-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '19',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6284',
  },
  {
    id: '6316',
    idw: '328',
    nazwa: 'Awantura w Chioggi',
    rezyseria: 'reż. Paweł Aigner',
    czas_trwania_min: '135',
    data: '15-08-2022',
    godzina: '18:00',
    miejsce: 'Gdański Teatr Szekspirowski',
    miejsca_dostepne: '328',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6316',
  },
  {
    id: '6294',
    idw: '293',
    nazwa: 'Niezwyciężony',
    rezyseria: 'reż. Jarosław Tumidajski',
    czas_trwania_min: '150',
    data: '17-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '100',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6294',
  },
  {
    id: '6289',
    idw: '339',
    nazwa: 'Upiory',
    rezyseria: 'reż. Olga Grzelak',
    czas_trwania_min: '100',
    data: '17-08-2022',
    godzina: '19:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '115',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6289',
  },
  {
    id: '6295',
    idw: '293',
    nazwa: 'Niezwyciężony',
    rezyseria: 'reż. Jarosław Tumidajski',
    czas_trwania_min: '150',
    data: '18-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '64',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6295',
  },
  {
    id: '6288',
    idw: '337',
    nazwa: 'Sceny z egzekucji',
    rezyseria: 'reż. Adam Orzechowski',
    czas_trwania_min: '105',
    data: '18-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '26',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6288',
  },
  {
    id: '6290',
    idw: '339',
    nazwa: 'Upiory',
    rezyseria: 'reż. Olga Grzelak',
    czas_trwania_min: '100',
    data: '18-08-2022',
    godzina: '19:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '41',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6290',
  },
  {
    id: '6296',
    idw: '293',
    nazwa: 'Niezwyciężony',
    rezyseria: 'reż. Jarosław Tumidajski',
    czas_trwania_min: '150',
    data: '19-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '83',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6296',
  },
  {
    id: '6285',
    idw: '337',
    nazwa: 'Sceny z egzekucji',
    rezyseria: 'reż. Adam Orzechowski',
    czas_trwania_min: '105',
    data: '19-08-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '51',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6285',
  },
  {
    id: '6291',
    idw: '339',
    nazwa: 'Upiory',
    rezyseria: 'reż. Olga Grzelak',
    czas_trwania_min: '100',
    data: '19-08-2022',
    godzina: '19:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '117',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6291',
  },
  {
    id: '6286',
    idw: '337',
    nazwa: 'Sceny z egzekucji',
    rezyseria: 'reż. Adam Orzechowski',
    czas_trwania_min: '105',
    data: '20-08-2022',
    godzina: '18:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '51',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6286',
  },
  {
    id: '6292',
    idw: '339',
    nazwa: 'Upiory',
    rezyseria: 'reż. Olga Grzelak',
    czas_trwania_min: '100',
    data: '20-08-2022',
    godzina: '18:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '109',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6292',
  },
  {
    id: '6287',
    idw: '337',
    nazwa: 'Sceny z egzekucji',
    rezyseria: 'reż. Adam Orzechowski',
    czas_trwania_min: '105',
    data: '21-08-2022',
    godzina: '18:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '52',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6287',
  },
  {
    id: '6293',
    idw: '339',
    nazwa: 'Upiory',
    rezyseria: 'reż. Olga Grzelak',
    czas_trwania_min: '100',
    data: '21-08-2022',
    godzina: '18:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6293',
  },
  {
    id: '6378',
    idw: '329',
    nazwa: 'Szelmostwa Lisa Witalisa',
    rezyseria: 'reż. Joanna Zdrada',
    czas_trwania_min: '50',
    data: '20-09-2022',
    godzina: '18:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '109',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6378',
  },
  {
    id: '6324',
    idw: '329',
    nazwa: 'Szelmostwa Lisa Witalisa',
    rezyseria: 'reż. Joanna Zdrada',
    czas_trwania_min: '50',
    data: '21-09-2022',
    godzina: '11:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '122',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6324',
  },
  {
    id: '6325',
    idw: '329',
    nazwa: 'Szelmostwa Lisa Witalisa',
    rezyseria: 'reż. Joanna Zdrada',
    czas_trwania_min: '50',
    data: '22-09-2022',
    godzina: '11:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6325',
  },
  {
    id: '6327',
    idw: '284',
    nazwa: 'Śmierć komiwojażera',
    rezyseria: 'reż. Radosław Stępień',
    czas_trwania_min: '130',
    data: '22-09-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '82',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6327',
  },
  {
    id: '6332',
    idw: '331',
    nazwa: 'Resztki',
    rezyseria: 'reż. Ewelina Marciniak',
    czas_trwania_min: '120',
    data: '23-09-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '68',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6332',
  },
  {
    id: '6328',
    idw: '284',
    nazwa: 'Śmierć komiwojażera',
    rezyseria: 'reż. Radosław Stępień',
    czas_trwania_min: '130',
    data: '24-09-2022',
    godzina: '17:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '116',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6328',
  },
  {
    id: '6330',
    idw: '331',
    nazwa: 'Resztki',
    rezyseria: 'reż. Ewelina Marciniak',
    czas_trwania_min: '120',
    data: '24-09-2022',
    godzina: '20:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '68',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6330',
  },
  {
    id: '6331',
    idw: '331',
    nazwa: 'Resztki',
    rezyseria: 'reż. Ewelina Marciniak',
    czas_trwania_min: '120',
    data: '25-09-2022',
    godzina: '17:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '70',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6331',
  },
  {
    id: '6329',
    idw: '284',
    nazwa: 'Śmierć komiwojażera',
    rezyseria: 'reż. Radosław Stępień',
    czas_trwania_min: '130',
    data: '25-09-2022',
    godzina: '19:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '120',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6329',
  },
  {
    id: '6336',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '29-09-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6336',
  },
  {
    id: '6335',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '30-09-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '2',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6335',
  },
  {
    id: '6333',
    idw: '335',
    nazwa: 'Drganie Jednej Struny',
    rezyseria: 'Katarzyna Chmielewska, Magdalena Reiter, Jakub Truszkowski',
    czas_trwania_min: {},
    data: '30-09-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '66',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6333',
  },
  {
    id: '6340',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '30-09-2022',
    godzina: '19:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '113',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6340',
  },
  {
    id: '6341',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '01-10-2022',
    godzina: '18:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '88',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6341',
  },
  {
    id: '6337',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '01-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '3',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6337',
  },
  {
    id: '6334',
    idw: '335',
    nazwa: 'Drganie Jednej Struny',
    rezyseria: 'Katarzyna Chmielewska, Magdalena Reiter, Jakub Truszkowski',
    czas_trwania_min: {},
    data: '01-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '67',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6334',
  },
  {
    id: '6342',
    idw: '348',
    nazwa: 'Kim jest pan Schmitt?',
    rezyseria: 'reż. Jan Hussakowski',
    czas_trwania_min: '120',
    data: '02-10-2022',
    godzina: '18:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '111',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6342',
  },
  {
    id: '6338',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '04-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '61',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6338',
  },
  {
    id: '6339',
    idw: '340',
    nazwa: 'WSOPOTWZIĘCI',
    rezyseria: 'reż. Łukasz Czuj',
    czas_trwania_min: {},
    data: '05-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '65',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6339',
  },
  {
    id: '6343',
    idw: '334',
    nazwa: 'Nieczułość',
    rezyseria: 'reż. Lena Frankiewicz ',
    czas_trwania_min: '115',
    data: '05-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '88',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6343',
  },
  {
    id: '6344',
    idw: '334',
    nazwa: 'Nieczułość',
    rezyseria: 'reż. Lena Frankiewicz ',
    czas_trwania_min: '115',
    data: '07-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '82',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6344',
  },
  {
    id: '6345',
    idw: '334',
    nazwa: 'Nieczułość',
    rezyseria: 'reż. Lena Frankiewicz ',
    czas_trwania_min: '115',
    data: '08-10-2022',
    godzina: '18:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '75',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6345',
  },
  {
    id: '6346',
    idw: '334',
    nazwa: 'Nieczułość',
    rezyseria: 'reż. Lena Frankiewicz ',
    czas_trwania_min: '115',
    data: '09-10-2022',
    godzina: '18:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '92',
    url: 'https://bilety.teatrwybrzeze.pl/nienumerowane.html?id=6346',
  },
  {
    id: '6350',
    idw: '310',
    nazwa: 'Inteligenci',
    rezyseria: 'reż. Radosław B. Maciąg',
    czas_trwania_min: '120',
    data: '12-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '58',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6350',
  },
  {
    id: '6349',
    idw: '310',
    nazwa: 'Inteligenci',
    rezyseria: 'reż. Radosław B. Maciąg',
    czas_trwania_min: '120',
    data: '13-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '39',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6349',
  },
  {
    id: '6353',
    idw: '347',
    nazwa: 'Czego nie widać',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '120',
    data: '13-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6353',
  },
  {
    id: '6354',
    idw: '347',
    nazwa: 'Czego nie widać',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '120',
    data: '14-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '29',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6354',
  },
  {
    id: '6347',
    idw: '349',
    nazwa: 'Koło sprawy Bożej',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: {},
    data: '14-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6347',
  },
  {
    id: '6351',
    idw: '310',
    nazwa: 'Inteligenci',
    rezyseria: 'reż. Radosław B. Maciąg',
    czas_trwania_min: '120',
    data: '15-10-2022',
    godzina: '17:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '51',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6351',
  },
  {
    id: '6348',
    idw: '349',
    nazwa: 'Koło sprawy Bożej',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: {},
    data: '15-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '60',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6348',
  },
  {
    id: '6355',
    idw: '347',
    nazwa: 'Czego nie widać',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '120',
    data: '15-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6355',
  },
  {
    id: '6352',
    idw: '310',
    nazwa: 'Inteligenci',
    rezyseria: 'reż. Radosław B. Maciąg',
    czas_trwania_min: '120',
    data: '16-10-2022',
    godzina: '17:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '58',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6352',
  },
  {
    id: '6356',
    idw: '347',
    nazwa: 'Czego nie widać',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '120',
    data: '16-10-2022',
    godzina: '18:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '30',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6356',
  },
  {
    id: '6380',
    idw: '349',
    nazwa: 'Koło sprawy Bożej',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: {},
    data: '16-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '91',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6380',
  },
  {
    id: '6357',
    idw: '347',
    nazwa: 'Czego nie widać',
    rezyseria: 'reż. Jan Klata',
    czas_trwania_min: '120',
    data: '18-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6357',
  },
  {
    id: '6381',
    idw: '349',
    nazwa: 'Koło sprawy Bożej',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: {},
    data: '18-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '108',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6381',
  },
  {
    id: '6382',
    idw: '349',
    nazwa: 'Koło sprawy Bożej',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: {},
    data: '19-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '97',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6382',
  },
  {
    id: '6358',
    idw: '328',
    nazwa: 'Awantura w Chioggi',
    rezyseria: 'reż. Paweł Aigner',
    czas_trwania_min: '135',
    data: '20-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6358',
  },
  {
    id: '6364',
    idw: '326',
    nazwa: 'Niepokój',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '75',
    data: '21-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '61',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6364',
  },
  {
    id: '6361',
    idw: '320',
    nazwa: 'Emigrantki',
    rezyseria: 'reż. Elżbieta Depta',
    czas_trwania_min: '90',
    data: '21-10-2022',
    godzina: '19:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '120',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6361',
  },
  {
    id: '6365',
    idw: '326',
    nazwa: 'Niepokój',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '75',
    data: '22-10-2022',
    godzina: '16:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6365',
  },
  {
    id: '6362',
    idw: '320',
    nazwa: 'Emigrantki',
    rezyseria: 'reż. Elżbieta Depta',
    czas_trwania_min: '90',
    data: '22-10-2022',
    godzina: '18:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '115',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6362',
  },
  {
    id: '6359',
    idw: '328',
    nazwa: 'Awantura w Chioggi',
    rezyseria: 'reż. Paweł Aigner',
    czas_trwania_min: '135',
    data: '22-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '41',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6359',
  },
  {
    id: '6360',
    idw: '328',
    nazwa: 'Awantura w Chioggi',
    rezyseria: 'reż. Paweł Aigner',
    czas_trwania_min: '135',
    data: '23-10-2022',
    godzina: '16:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '32',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6360',
  },
  {
    id: '6363',
    idw: '320',
    nazwa: 'Emigrantki',
    rezyseria: 'reż. Elżbieta Depta',
    czas_trwania_min: '90',
    data: '23-10-2022',
    godzina: '18:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '122',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6363',
  },
  {
    id: '6366',
    idw: '326',
    nazwa: 'Niepokój',
    rezyseria: 'reż. Grzegorz Wiśniewski',
    czas_trwania_min: '75',
    data: '23-10-2022',
    godzina: '20:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '70',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6366',
  },
  {
    id: '6367',
    idw: '324',
    nazwa: 'Faust',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: '125',
    data: '25-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '56',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6367',
  },
  {
    id: '6368',
    idw: '324',
    nazwa: 'Faust',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: '125',
    data: '26-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6368',
  },
  {
    id: '6369',
    idw: '324',
    nazwa: 'Faust',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: '125',
    data: '27-10-2022',
    godzina: '18:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '0',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6369',
  },
  {
    id: '6372',
    idw: '263',
    nazwa: 'Reset',
    rezyseria: 'reż. Anna Gryszkówna',
    czas_trwania_min: '95',
    data: '27-10-2022',
    godzina: '20:30',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '116',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6372',
  },
  {
    id: '6370',
    idw: '324',
    nazwa: 'Faust',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: '125',
    data: '28-10-2022',
    godzina: '18:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '59',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6370',
  },
  {
    id: '6375',
    idw: '285',
    nazwa: 'Fedra',
    rezyseria: 'Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '28-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '21',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6375',
  },
  {
    id: '6379',
    idw: '324',
    nazwa: 'Faust',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: '125',
    data: '29-10-2022',
    godzina: '16:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '46',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6379',
  },
  {
    id: '6376',
    idw: '285',
    nazwa: 'Fedra',
    rezyseria: 'Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '29-10-2022',
    godzina: '19:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '68',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6376',
  },
  {
    id: '6373',
    idw: '263',
    nazwa: 'Reset',
    rezyseria: 'reż. Anna Gryszkówna',
    czas_trwania_min: '95',
    data: '29-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '120',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6373',
  },
  {
    id: '6371',
    idw: '324',
    nazwa: 'Faust',
    rezyseria: 'reż. Radek Stępień',
    czas_trwania_min: '125',
    data: '30-10-2022',
    godzina: '16:00',
    miejsce: 'Scena Malarnia',
    miejsca_dostepne: '48',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6371',
  },
  {
    id: '6377',
    idw: '285',
    nazwa: 'Fedra',
    rezyseria: 'Grzegorz Wiśniewski',
    czas_trwania_min: '135',
    data: '30-10-2022',
    godzina: '18:00',
    miejsce: 'Scena Kameralna',
    miejsca_dostepne: '71',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6377',
  },
  {
    id: '6374',
    idw: '263',
    nazwa: 'Reset',
    rezyseria: 'reż. Anna Gryszkówna',
    czas_trwania_min: '95',
    data: '30-10-2022',
    godzina: '19:00',
    miejsce: 'Stara Apteka',
    miejsca_dostepne: '122',
    url: 'https://bilety.teatrwybrzeze.pl/numerowane.html?id=6374',
  },
];
